export interface TreeNode {
  id: number
  title: string
  parentId: number | null
  hasChild: boolean
  kbId: number
  kbName: string
  spaceId: number
  spaceName: string
  children?: TreeNode[]
}

export interface TreeVisualization {
  nodes: TreeNode[]
  edges: Array<{ from: number; to: number }>
  stats: {
    totalNodes: number
    totalDocs: number
    maxDepth: number
    leafNodes: number
  }
}

export function visualizeTree(tree: TreeNode[]): TreeVisualization {
  const nodes: TreeNode[] = []
  const edges: Array<{ from: number; to: number }> = []
  let maxDepth = 0

  function processNode(node: TreeNode, depth: number = 0): void {
    maxDepth = Math.max(maxDepth, depth)
    nodes.push(node)
    if (node.children) {
      for (const child of node.children) {
        edges.push({ from: node.id, to: child.id })
        processNode(child, depth + 1)
      }
    }
  }

  for (const root of tree) {
    processNode(root)
  }

  const leafNodes = nodes.filter(n => !n.hasChild).length

  return {
    nodes,
    edges,
    stats: {
      totalNodes: nodes.length,
      totalDocs: nodes.length,
      maxDepth,
      leafNodes,
    },
  }
}

export function exportAsMarkdown(tree: TreeNode[], kbName: string): string {
  const lines: string[] = []
  lines.push(`# ${kbName} - 目录结构`)
  lines.push('')
  lines.push('> Generated by KM-Portal Wizard')
  lines.push('')
  lines.push('## 目录大纲')
  lines.push('')

  function renderNode(node: TreeNode, prefix: string = '', isLast: boolean = true): void {
    const connector = isLast ? '└── ' : '├── '
    const childPrefix = prefix + (isLast ? '    ' : '│   ')
    lines.push(`${prefix}${connector}${node.title}`)

    if (node.children && node.children.length > 0) {
      const children = node.children
      for (let i = 0; i < children.length; i++) {
        renderNode(children[i], childPrefix, i === children.length - 1)
      }
    }
  }

  for (let i = 0; i < tree.length; i++) {
    renderNode(tree[i], '', i === tree.length - 1)
  }

  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push(`*共 ${getDocCount(tree)} 个文档*`)

  return lines.join('\n')
}

export function getDocCount(tree: TreeNode[]): number {
  let count = 0

  function countNodes(nodes: TreeNode[]): void {
    for (const node of nodes) {
      count++
      if (node.children) {
        countNodes(node.children)
      }
    }
  }

  countNodes(tree)
  return count
}

export function buildTreeFromFlat(flatNodes: Array<{
  id: number
  title: string
  parentId: number | null
  hasChild: boolean
  kbId: number
  kbName: string
  spaceId: number
  spaceName: string
}>): TreeNode[] {
  const nodeMap = new Map<number, TreeNode>()
  const roots: TreeNode[] = []

  for (const item of flatNodes) {
    const node: TreeNode = {
      ...item,
      children: [],
    }
    nodeMap.set(item.id, node)
  }

  for (const node of nodeMap.values()) {
    if (node.parentId === null || !nodeMap.has(node.parentId)) {
      roots.push(node)
    } else {
      const parent = nodeMap.get(node.parentId)
      if (parent) {
        parent.children = parent.children || []
        parent.children.push(node)
      }
    }
  }

  return roots
}