import archiver from 'archiver';
import { Writable } from 'stream';

export interface SkillPackageOptions {
  skillId: string;
  skillName: string;
  description: string;
  triggerWords: string[];
  kbId: number;
  kbName: string;
  content: string;
  /** v1.9.0: API Key (注入到 config/user.json 与 SKILL.md) */
  apiKey?: string;
  /** v1.9.0: KM-Portal 代理地址（默认 http://10.101.10.50:5053/api） */
  portalBaseUrl?: string;
}

// v1.7.4 默认 trigger 词兜底：用户未指定时提供基础查询词
// 避免生成的 Skill 包 trigger: [] 空列表（虽然合法但语义弱）
const DEFAULT_TRIGGER_WORDS: ReadonlyArray<string> = [
  '查询', '搜索', 'search', 'query', '知识库', 'knowledge base',
  'kb', 'doc', '文档',
];

// v1.7.1 安全目录名：与 routes/skill.ts 的 safeName 保持一致
function safeName(name: string): string {
  return name
    .replace(/[^\w\u4e00-\u9fa5\-_.]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase() || 'skill';
}

// v1.7.1 YAML 字符串转义（双引号包裹 + 反斜杠转义内部引号）
function yamlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function buildSkillMd(options: SkillPackageOptions): string {
  // v1.7.4 trigger 兜底：空列表时使用默认 trigger 词
  const effectiveTriggers = options.triggerWords.length > 0
    ? options.triggerWords
    : DEFAULT_TRIGGER_WORDS;
  // v1.7.1 YAML frontmatter 规范化：description 用双引号、trigger 改列表
  const triggerList = effectiveTriggers.map(w => `  - "${yamlEscape(w)}"`).join('\n');
  const frontmatter = [
    '---',
    `name: "${yamlEscape(options.skillName)}"`,
    `description: "${yamlEscape(options.description)}"`,
    'trigger:',
    triggerList,
    `kb_id: ${options.kbId}`,
    `version: "1.0.0"`,
    '---',
    '',
  ].join('\n');
  return frontmatter + options.content;
}

function buildReadme(options: SkillPackageOptions): string {
  // v1.7.4 同步 trigger 兜底逻辑
  const effectiveTriggers = options.triggerWords.length > 0
    ? options.triggerWords
    : DEFAULT_TRIGGER_WORDS;
  return `# ${options.skillName}

## 简介

${options.description || `Knowledge Base Skill for ${options.kbName}`}

## 知识库信息

- **KB ID**: ${options.kbId}
- **KB Name**: ${options.kbName}

## 安装

1. 确保已安装 Python 3.8+
2. 安装依赖：\`pip install -r requirements.txt\`
3. 配置：编辑 \`config/user.json\` 填入知识库信息

## 使用

\`\`\`python
from scripts.kb_client import KMClient

client = KMClient(kb_id=${options.kbId})
result = client.get_tree()
print(result)
\`\`\`

## 触发词

${effectiveTriggers.map(w => `- ${w}`).join('\n')}

---
Generated by KM-Portal
`;
}

function buildUserConfig(options: SkillPackageOptions): string {
  // v1.9.0: 默认指向 KM-Portal 代理（10.101.10.50:5053），可通过 KM_PORTAL_URL 覆盖
  const portalBaseUrl = options.portalBaseUrl
    || process.env.KM_PORTAL_URL
    || process.env.PORTAL_BASE_URL
    || 'http://10.101.10.50:5053/api'
  return JSON.stringify({
    kb_id: options.kbId,
    kb_name: options.kbName,
    km_api_url: portalBaseUrl,
    api_key: options.apiKey || '',
  }, null, 2);
}

function buildKbClientPy(): string {
  return `# -*- coding: utf-8 -*-
"""
kb_client.py - Knowledge Base HTTP API Client (v1.9.0)
调用 KM-Portal 代理(/api/kb/*), 走 POST + Bearer API Key 鉴权
"""

import json
import time
import uuid
import requests
from typing import Dict, Any, List, Optional
from pathlib import Path

DEFAULT_TIMEOUT = 30

CONFIG_DIR = Path(__file__).parent.parent / "config"
USER_CONFIG_FILE = CONFIG_DIR / "user.json"


def _load_config() -> Dict[str, Any]:
    """Load user configuration from config/user.json"""
    if not USER_CONFIG_FILE.exists():
        return {}
    try:
        with open(USER_CONFIG_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return {}


def get_km_api_url() -> str:
    """Get KM-Portal proxy URL from config"""
    config = _load_config()
    return config.get("km_api_url", "http://10.101.10.50:5053/api")


def get_api_key() -> str:
    """Get API Key from config"""
    return _load_config().get("api_key", "")


def get_kb_config() -> Dict[str, Any]:
    """Get KB config from config/user.json"""
    config = _load_config()
    return {
        "kb_id": config.get("kb_id"),
        "kb_name": config.get("kb_name"),
    }


class KMClient:
    """Knowledge Base HTTP API Client (POST + Bearer)"""

    def __init__(self, kb_id: Optional[int] = None):
        self.km_api_url = get_km_api_url()
        if self.km_api_url and not self.km_api_url.endswith("/"):
            self.km_api_url += "/"
        self.kb_id = kb_id

    def _get_headers(self) -> Dict[str, str]:
        """Generate request headers (v1.9.0: Bearer API Key)"""
        api_key = get_api_key()
        headers = {
            "Content-Type": "application/json",
            "requestId": f"req-{int(time.time())}-{uuid.uuid4().hex[:8]}"
        }
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        return headers

    def _request(self, action: str, params: Optional[Dict] = None) -> Dict[str, Any]:
        """Send API request (统一 POST, 适配 KM-Portal /api/kb/* 代理)"""
        if not self.km_api_url:
            return {
                "success": False,
                "error": "KM_API not configured",
                "code": "NOT_CONFIGURED"
            }

        url = f"{self.km_api_url}kb/{action}"
        start_time = time.time()

        body = {}
        if self.kb_id:
            body["kb_id"] = self.kb_id
        if params:
            body.update(params)

        try:
            headers = self._get_headers()
            # v1.9.0: 全部用 POST（KM-Portal 代理路由统一 POST 包装）
            response = requests.post(url, headers=headers, json=body, timeout=DEFAULT_TIMEOUT)

            latency_ms = int((time.time() - start_time) * 1000)

            try:
                result = response.json()
            except json.JSONDecodeError:
                return {
                    "success": False,
                    "error": f"Response parse failed: {response.text[:200]}",
                    "request_id": None,
                    "latency_ms": latency_ms
                }

            if result.get("success") is True:
                return {
                    "success": True,
                    "data": result.get("data"),
                    "msg": result.get("msg"),
                    "request_id": headers["requestId"],
                    "latency_ms": latency_ms
                }
            else:
                return {
                    "success": False,
                    "error": result.get("error", "Request failed"),
                    "code": result.get("code"),
                    "request_id": headers["requestId"],
                    "latency_ms": latency_ms
                }

        except requests.Timeout:
            return {
                "success": False,
                "error": "Request timeout",
                "code": "TIMEOUT",
                "latency_ms": int((time.time() - start_time) * 1000)
            }
        except requests.RequestException as e:
            return {
                "success": False,
                "error": str(e),
                "code": "REQUEST_ERROR",
                "latency_ms": int((time.time() - start_time) * 1000)
            }

    def get_tree(self, kb_id: Optional[int] = None, parent_id: Optional[int] = None) -> Dict[str, Any]:
        """Get directory tree"""
        data = {}
        if kb_id is not None:
            data["kb_id"] = kb_id
        if parent_id is not None:
            data["parent_id"] = parent_id
        return self._request("tree", data)

    def get_content(self, content_ids: List[int], content_type: str = "markdown") -> Dict[str, Any]:
        """Get document content"""
        return self._request("content", {
            "content_ids": content_ids,
            "content_type": content_type
        })

    def create_content(self, kb_id: int, title: str, content: str,
                       content_type: str = "markdown", parent_id: Optional[int] = None) -> Dict[str, Any]:
        """Create document"""
        data = {
            "kb_id": kb_id,
            "title": title,
            "content_type": content_type,
            "content": content
        }
        if parent_id is not None:
            data["parent_id"] = parent_id
        return self._request("contents/create", data)

    def update_content(self, content_id: int, title: str, content: str,
                       content_type: str = "markdown") -> Dict[str, Any]:
        """Update document"""
        return self._request("contents/update", {
            "content_id": content_id,
            "title": title,
            "content_type": content_type,
            "content": content
        })

    def delete_content(self, content_id: int) -> Dict[str, Any]:
        """Delete document"""
        return self._request("contents/delete", {
            "content_id": content_id
        })

    def test_connection(self) -> Dict[str, Any]:
        """Test connection"""
        result = self._request("info", {})
        if result.get("success"):
            return {
                "success": True,
                "message": "Connection successful",
                "data": result.get("data")
            }
        return {
            "success": False,
            "message": "Connection failed",
            "error": result.get("error")
        }


def list_kbs() -> Dict[str, Any]:
    """Get authorized knowledge base list"""
    client = KMClient()
    return client._request("info", {})


def get_tree(kb_id: int, parent_id: Optional[int] = None) -> Dict[str, Any]:
    """Get directory tree"""
    client = KMClient(kb_id=kb_id)
    return client.get_tree(kb_id, parent_id)


def get_content(content_ids: List[int], content_type: str = "markdown") -> Dict[str, Any]:
    """Get document content"""
    client = KMClient()
    return client.get_content(content_ids, content_type)


def create_content(kb_id: int, title: str, content: str,
                   content_type: str = "markdown",
                   parent_id: Optional[int] = None) -> Dict[str, Any]:
    """Create document"""
    client = KMClient(kb_id=kb_id)
    return client.create_content(kb_id, title, content, content_type, parent_id)


def update_content(content_id: int, title: str, content: str,
                   content_type: str = "markdown") -> Dict[str, Any]:
    """Update document"""
    client = KMClient()
    return client.update_content(content_id, title, content, content_type)


def delete_content(content_id: int) -> Dict[str, Any]:
    """Delete document"""
    client = KMClient()
    return client.delete_content(content_id)


def test_connection() -> Dict[str, Any]:
    """Test connection"""
    client = KMClient()
    return client.test_connection()
`;
}

function buildInitPy(): string {
  // v1.7.1 跳过空 __init__.py（Python 包识别不需要此文件）
  return '';
}

function buildRequirementsTxt(): string {
  return 'requests>=2.28.0\n';
}

export async function buildSkillZip(options: SkillPackageOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const output = new Writable({
      write(chunk: Buffer | string, _encoding: string, callback: () => void) {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
        callback();
      }
    });

    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('finish', () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on('error', (err) => {
      reject(err);
    });

    archive.pipe(output);

    // v1.7.1 使用统一 safeName 派生规则（与 routes/skill.ts 一致）
    const skillDir = safeName(options.skillName);

    archive.append(buildSkillMd(options), { name: `${skillDir}/SKILL.md` });
    archive.append(buildReadme(options), { name: `${skillDir}/README.md` });
    archive.append(buildUserConfig(options), { name: `${skillDir}/config/user.json` });
    archive.append(buildKbClientPy(), { name: `${skillDir}/scripts/kb_client.py` });
    // v1.7.1 跳过空 __init__.py
    const initContent = buildInitPy();
    if (initContent) {
      archive.append(initContent, { name: `${skillDir}/scripts/__init__.py` });
    }
    archive.append(buildRequirementsTxt(), { name: `${skillDir}/requirements.txt` });

    archive.finalize();
  });
}